
name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  CodeCov:
    # 运行环境
    runs-on: ubuntu-latest
    # 任务步骤
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.2.1

      - name: Install package
        run: pnpm install
      
      - name: Run test coverage
        run: pnpm coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with: 
          directory: coverage
          token: ${{ secrets.CODECOV_TOKEN }}