name: Publish To Npm

on: 
  push:
    branches: [release]

jobs:
  Publish:
    runs-on: ubuntu-latest
    environment: npm
    steps: 
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.2.1

      - name: Install package
        run: pnpm install

      - name: Run build
        run: pnpm build

      - name: Publish to npm
        uses: primer/publish@3.0.0
        env: 
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}